
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imcxvnivqrckgjrimzck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltY3h2bml2cXJja2dqcmltemNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NjM4NjIsImV4cCI6MjA1ODUzOTg2Mn0.BGIWnSFMuz4AR0FuYeH8kRvRwoa72x6JMtdnTbOE6k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
    detectSessionInUrl: true,
    flowType: 'implicit'
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
    // Add a small delay on DB operations to ensure they complete properly
    fetch: (url: RequestInfo | URL, options?: RequestInit) => {
      return new Promise((resolve) => {
        setTimeout(() => {
          // Fix type issue with proper Response type
          resolve(fetch(url, options));
        }, 50); // Small delay to ensure operations have time to complete
      });
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Helper functions for type casting
export const handleSupabaseResponse = <T>(data: any): T[] => {
  if (!data || data.error) {
    return [];
  }
  return data as T[];
};

export const handleSupabaseResponseSingle = <T>(data: any): T | null => {
  if (!data || data.error) {
    return null;
  }
  return data as T;
};
